apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
   - synapse-admin.yaml
   - synapse-admin-ingressroute.yaml

configMapGenerator:
  - name: synapse-admin-config
    namespace: app-matrix
    files:
      - config/synapse-admin-nginx.conf
      - config/synapse-admin-config.json
