apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
   - synapse-admin.yaml
   - ingressroute.yaml

configMapGenerator:
  - name: synapse-admin-config
    namespace: app-matrix
    files:
      - config/config.json
