apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zerobyte
  namespace: app-zerobyte

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`zerobyte.cluster.arpa`)
      kind: Rule
      services:
        - name: zerobyte
          namespace: app-zerobyte
          port: 4096
  tls:
    secretName: traefik-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  namespace: app-zerobyte
spec:
  secretName: traefik-tls
  duration: 672h # 28d
  renewBefore: 168h # 7d
  issuerRef:
    name: custom-ca-cluster-issuer
    kind: ClusterIssuer
  commonName: "zerobyte.cluster.arpa"
  dnsNames:
    - "zerobyte.cluster.arpa"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-ingress-controller
  namespace: app-zerobyte

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: traefik-system
