apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - zerobyte.yaml
  - ingressroute.yaml

configMapGenerator:
  - name: zerobyte-config
    namespace: app-zerobyte
    envs:
      - zerobyte-config.env
