logLevel: error
logFormat: json
route:
  routes:
    - match:
        - receiver: loki
receivers:
  - name: loki
    loki:
      streamLabels:
        job: kubernetes-events
        namespace: "{{ .InvolvedObject.Namespace }}"
        kind: "{{ .InvolvedObject.Kind }}"
        name: "{{ .InvolvedObject.Name }}"
        reason: "{{ .Reason }}"
        type: "{{ .Type }}"
      url: http://loki.monitoring-system.svc.cluster.local:3100/loki/api/v1/push
