apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - livekit.yaml
  - livekit-proxy.yaml
  - lk-jwt-service.yaml
  - sealed-livekit-secrets.yaml
  - tunnel.yaml

configMapGenerator:
  - name: livekit-config
    namespace: app-matrix
    files:
      - config/livekit.yaml

  - name: livekit-nginx
    namespace: app-matrix
    files:
      - default.conf=config/livekit-nginx.conf
