apiVersion: v1
kind: Service
metadata:
  name: actual
  namespace: app-actual

spec:
  ports:
    - name: http
      port: 5006
  selector:
    app: actual
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: actual
  namespace: app-actual

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`actual.cluster.arpa`)
      kind: Rule
      services:
        - name: actual
          namespace: app-actual
          port: 5006
  tls:
    secretName: traefik-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  namespace: app-actual
spec:
  secretName: traefik-tls
  duration: 672h # 28d
  renewBefore: 168h # 7d
  issuerRef:
    name: custom-ca-cluster-issuer
    kind: ClusterIssuer
  commonName: "actual.cluster.arpa"
  dnsNames:
    - "actual.cluster.arpa"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-ingress-controller
  namespace: app-actual

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: traefik-system
