apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - actual.yaml
  - ingressroute.yaml

configMapGenerator:
  - name: actual-config
    namespace: app-actual
    envs:
      - actual-config.env