apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cnpg-cluster.yaml
  - sealed-meowlnir-secrets.yaml
  - meowlnir.yaml
  - service.yaml

configMapGenerator:
  - name: meowlnir-config
    namespace: app-matrix
    files:
      - meowlnir-config.yaml=config/meowlnir-config.yaml
      - meowlnir-registration.yml=config/meowlnir-registration.yml
