# Meowlnir Appservice Registration
# This file must be registered with Synapse in homeserver.yaml under app_service_config_files
id: meowlnir
url: http://meowlnir.app-matrix.svc:29339
as_token: ${MEOWLNIR_AS_TOKEN}
hs_token: ${MEOWLNIR_HS_TOKEN}
sender_localpart: meowlnir
rate_limited: false

namespaces:
  users:
    # Meowlnir bot user
    - regex: "^@meowlnir:borooka\\.ee$"
      exclusive: true
  rooms: []
  aliases: []

# End-to-end encryption support flags
# Required for Meowlnir to work in encrypted rooms
de.sorunome.msc2409.push_ephemeral: true
push_ephemeral: true
org.matrix.msc3202: true
io.element.msc4190: true
