# Jitsi Meet IngressRoute and TLS Certificate
# Handles traffic for meet.cluster.arpa
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jitsi-meet
  namespace: app-matrix
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`meet.cluster.arpa`)
      kind: Rule
      services:
        - name: jitsi-web
          port: http
  tls:
    secretName: jitsi-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jitsi-cert
  namespace: app-matrix
spec:
  secretName: jitsi-tls
  duration: 672h # 28d
  renewBefore: 168h # 7d
  issuerRef:
    name: custom-ca-cluster-issuer
    kind: ClusterIssuer
  commonName: "meet.cluster.arpa"
  dnsNames:
    - "meet.cluster.arpa"
