# Synapse IngressRoute and TLS Certificate
# Handles traffic for matrix.cluster.arpa
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: synapse
  namespace: app-matrix
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`matrix.cluster.arpa`)
      kind: Rule
      services:
        - name: synapse
          port: http
  tls:
    secretName: synapse-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: synapse-cert
  namespace: app-matrix
spec:
  secretName: synapse-tls
  duration: 672h # 28d
  renewBefore: 168h # 7d
  issuerRef:
    name: custom-ca-cluster-issuer
    kind: ClusterIssuer
  commonName: "matrix.cluster.arpa"
  dnsNames:
    - "matrix.cluster.arpa"
---
# Allow Traefik to access this namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-ingress-controller
  namespace: app-matrix
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: traefik-system
