apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cnpg-cluster.yaml
  - sealed-maubot-secrets.yaml
  - maubot.yaml
  - service.yaml

configMapGenerator:
  - name: maubot-config
    namespace: app-matrix
    files:
      - config.yaml=config/config.yaml
      - maubot-registration.yaml=config/maubot-registration.yaml

  - name: maubot-env
    namespace: app-matrix
    envs:
      - config/config.env
