apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - sealed-maubot-secrets.yaml
  - maubot.yaml
  - service.yaml
  - tunnel.yaml

configMapGenerator:
  - name: maubot-config
    namespace: app-matrix
    files:
      - config.yaml=config/config.yaml

  - name: maubot-env
    namespace: app-matrix
    envs:
      - config/config.env
