apiVersion: v1
kind: Service
metadata:
  name: maubot
  namespace: app-matrix
  labels:
    app: maubot
    app.kubernetes.io/name: maubot
    app.kubernetes.io/component: bot-manager
    app.kubernetes.io/part-of: matrix
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 29316
      targetPort: http
      protocol: TCP
  selector:
    app: maubot
