apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds
  - cloudflare
  - cnpg
  - flannel
  - longhorn
  - traefik
  - sealed-secrets
  - tailscale
  - nvidia
  - cert-manager
  - kubevirt
  - cdi
