# Matrix Meetings Appservice Registration
# This file must be registered with Synapse in homeserver.yaml under app_service_config_files
id: matrix-meetings
url: http://matrix-meetings-bot.app-matrix.svc:3000
as_token: ${MEETINGS_BOT_AS_TOKEN}
hs_token: ${MEETINGS_BOT_HS_TOKEN}
sender_localpart: meetings
rate_limited: false

namespaces:
  users:
    # Meetings bot user
    - regex: "^@meetings:borooka\\.ee$"
      exclusive: true
  rooms: []
  aliases: []

# End-to-end encryption support flags
# Note: Matrix-meetings bot does NOT support encrypted rooms,
# but these flags are included for consistency with other appservices
de.sorunome.msc2409.push_ephemeral: false
push_ephemeral: false
org.matrix.msc3202: false
