apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
   - well-known.yaml
   - ingressroute.yaml

configMapGenerator:
  - name: well-known-config
    namespace: app-matrix
    files:
      - server=config/server.json
      - client=config/client.json

  - name: well-known-nginx
    namespace: app-matrix
    files:
      - default.conf=config/nginx.conf
