apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: element
  namespace: app-matrix
spec:
  entryPoints:
    - tunnel
  routes:
    - match: Host(`element.borooka.ee`)
      kind: Rule
      priority: 1
      services:
        - name: element
          port: http
