apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prowlarr.yaml

configMapGenerator:
  - name: prowlarr-config
    namespace: app-servarr
    envs:
      - prowlarr-config.env
