apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - recyclarr.yaml

configMapGenerator:
  - name: recyclarr-config
    namespace: app-servarr
    files:
      - config/settings.yml
      - config/recyclarr.yml
