server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki.monitoring-system.svc.cluster.local:3100/loki/api/v1/push

scrape_configs:
  - job_name: minecraft-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spectrum
          component: "${COMPONENT}"
          __path__: /logs/*.log
    pipeline_stages:
      - multiline:
          firstline: '^\[\d{2}:\d{2}:\d{2}'
          max_wait_time: 3s
