# Mautrix Signal Appservice Registration
# This file must be registered with Synapse in homeserver.yaml under app_service_config_files
id: signal
url: http://mautrix-signal.app-matrix.svc:29328
as_token: ${SIGNAL_AS_TOKEN}
hs_token: ${SIGNAL_HS_TOKEN}
sender_localpart: signalbot
rate_limited: false

namespaces:
  users:
    - regex: "^@signal_.*:borooka\\.ee$"
      exclusive: true
    - regex: "^@signalbot:borooka\\.ee$"
      exclusive: true
  rooms: []
  aliases:
    - regex: "^#signal_.*:borooka\\.ee$"
      exclusive: true

# End-to-end encryption support flags
de.sorunome.msc2409.push_ephemeral: true
push_ephemeral: true
org.matrix.msc3202: true
