apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cnpg-cluster.yaml
  - sealed-mautrix-signal-secrets.yaml
  - mautrix-signal.yaml
  - service.yaml

configMapGenerator:
  - name: mautrix-signal-config
    namespace: app-matrix
    files:
      - config.yaml=config/config.yaml
      - signal-registration.yaml=config/registration.yaml
