apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg.yaml
  - keycloak.yaml
  - ingressroute.yaml
  - sealed-admin-secret.yaml
  - sealed-client-secrets.yaml

configMapGenerator:
  - name: keycloak-realm
    namespace: keycloak-system
    files:
      - cluster-realm.json=realm-cluster.json
    options:
      disableNameSuffixHash: true
