id: maubot-community
url: http://maubot.app-matrix.svc:29316
as_token: ${MAUBOT_AS_TOKEN}
hs_token: ${MAUBOT_HS_TOKEN}
sender_localpart: community
rate_limited: false

namespaces:
  users:
    - regex: "^@community:borooka\\.ee$"
      exclusive: true

  aliases:
    - exclusive: false
      regex: '^#[a-z0-9]+(?:-[a-z0-9]+)?:borooka\.ee$'

  rooms: []

# End-to-end encryption support
de.sorunome.msc2409.push_ephemeral: true
push_ephemeral: true
org.matrix.msc3202: true
io.element.msc4190: true
