id: discord
url: http://mautrix-discord.app-matrix.svc:29334
as_token: ${DISCORD_AS_TOKEN}
hs_token: ${DISCORD_HS_TOKEN}
sender_localpart: discordbot
rate_limited: false

namespaces:
  users:
    - regex: "^@discord_.*:borooka\\.ee$"
      exclusive: true
    - regex: "^@discordbot:borooka\\.ee$"
      exclusive: true
  rooms: []
  aliases:
    - regex: "^#discord_.*:borooka\\.ee$"
      exclusive: true

de.sorunome.msc2409.push_ephemeral: true
push_ephemeral: true
org.matrix.msc3202: true
io.element.msc4190: true
