# Mautrix Discord Appservice Registration
# This file must be registered with Synapse in homeserver.yaml under app_service_config_files
id: discord
url: http://mautrix-discord.app-matrix.svc:29334
as_token: ${DISCORD_AS_TOKEN}
hs_token: ${DISCORD_HS_TOKEN}
sender_localpart: discordbot
rate_limited: false

namespaces:
  users:
    - regex: "^@discord_.*:testing\\.borooka\\.ee$"
      exclusive: true
    - regex: "^@discordbot:testing\\.borooka\\.ee$"
      exclusive: true
  rooms: []
  aliases:
    - regex: "^#discord_.*:testing\\.borooka\\.ee$"
      exclusive: true

# End-to-end encryption support flags
de.sorunome.msc2409.push_ephemeral: true
push_ephemeral: true
org.matrix.msc3202: true
