apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cnpg-cluster.yaml
  - sealed-federation-tester-secrets.yaml
  - federation-tester.yaml
  - service.yaml
  - tunnel.yaml

configMapGenerator:
  - name: federation-tester-config
    namespace: app-matrix
    files:
      - config.yaml=config/config.yaml

  - name: federation-tester-env
    namespace: app-matrix
    envs:
      - config/config.env
