apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authelia-public
  namespace: app-authelia
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`auth.decentm.com`)
      kind: Rule
      services:
        - name: authelia
          port: 9091
