apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-authelia
resources:
  - namespace.yaml
  - cnpg.yaml
  - chart.yaml
  - sealed-secrets.yaml
  - sealed-smtp-secrets.yaml
  - lldap
  - middleware.yaml
  - ingress.yaml

configMapGenerator:
  - name: authelia-oidc-clients
    options:
      labels:
        app.kubernetes.io/name: authelia
        app.kubernetes.io/component: oidc-clients
      disableNameSuffixHash: true
    files:
      - config/clients.yaml
