apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-authelia
resources:
  - namespace.yaml
  - cnpg.yaml
  - chart.yaml
  - sealed-secrets.yaml
  - sealed-smtp-secrets.yaml
  - lldap
  - middleware.yaml
  - ingressroute.yaml
  - tunnel-borooka.yaml
  - tunnel-decentm.yaml
