apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cnpg.yaml
  - lldap-cnpg.yaml
  - lldap.yaml
  - lldap-ingressroute.yaml
  - redis.yaml
  - authelia.yaml
  - ingressroute.yaml
  - tunnel.yaml
  - sealed-authelia-secrets.yaml
  - sealed-lldap-secrets.yaml

commonLabels:
  app.kubernetes.io/part-of: authelia-stack

configMapGenerator:
  - name: authelia-config
    namespace: app-authelia
    files:
      - config/configuration.yml
