# Traefik IngressRoute for LLDAP web UI
# Internal cluster access only
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lldap
  namespace: app-authelia
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lldap.cluster.arpa`)
      kind: Rule
      services:
        - name: lldap
          namespace: app-authelia
          port: http
  tls:
    secretName: lldap-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lldap-cert
  namespace: app-authelia
spec:
  secretName: lldap-tls
  duration: 672h # 28d
  renewBefore: 168h # 7d
  issuerRef:
    name: custom-ca-cluster-issuer
    kind: ClusterIssuer
  commonName: "lldap.cluster.arpa"
  dnsNames:
    - "lldap.cluster.arpa"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-ingress-controller-lldap
  namespace: app-authelia
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: traefik-system
