apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus.yaml
  - loki.yaml
  - promtail.yaml
  - grafana.yaml
  - ingressroute.yaml
  - event-exporter.yaml
configMapGenerator:
  # Dashboards
  - name: grafana-dashboard-kubernetes-namespace
    namespace: monitoring-system
    files:
      - dashboards/kubernetes-namespace.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-spectrum
    namespace: monitoring-system
    files:
      - dashboards/spectrum.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-photoprism
    namespace: monitoring-system
    files:
      - dashboards/photoprism.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-traefik
    namespace: monitoring-system
    files:
      - dashboards/traefik.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  # Alerting - Contact Points
  - name: grafana-alerting-contactpoints
    namespace: monitoring-system
    files:
      - alerting/contactpoints.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
  # Alerting - Notification Policies
  - name: grafana-alerting-policies
    namespace: monitoring-system
    files:
      - alerting/policies.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
  # Alerting - Rules
  - name: grafana-alerting-rules-nodes
    namespace: monitoring-system
    files:
      - alerting/rules-nodes.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
  - name: grafana-alerting-rules-pods
    namespace: monitoring-system
    files:
      - alerting/rules-pods.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
  - name: grafana-alerting-rules-traefik
    namespace: monitoring-system
    files:
      - alerting/rules-traefik.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
  - name: grafana-alerting-rules-longhorn
    namespace: monitoring-system
    files:
      - alerting/rules-longhorn.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
  - name: grafana-alerting-rules-postgresql
    namespace: monitoring-system
    files:
      - alerting/rules-postgresql.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
  - name: grafana-alerting-rules-services
    namespace: monitoring-system
    files:
      - alerting/rules-services.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
