apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus.yaml
  - loki.yaml
  - promtail.yaml
  - grafana.yaml
  - ingressroute.yaml
configMapGenerator:
  - name: grafana-dashboard-kubernetes-namespace
    namespace: monitoring-system
    files:
      - dashboards/kubernetes-namespace.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-spectrum
    namespace: monitoring-system
    files:
      - dashboards/spectrum.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-photoprism
    namespace: monitoring-system
    files:
      - dashboards/photoprism.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
