apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-public
  namespace: app-whoami
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`whoami.decentm.com`)
      kind: Rule
      services:
        - name: whoami
          port: 8080
