apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-matrix-meetings-secrets.yaml
  - widget-deployment.yaml
  - widget-service.yaml
  - widget-tunnel.yaml
  - bot-deployment.yaml
  - bot-service.yaml

configMapGenerator:
  - name: matrix-meetings-widget-env
    namespace: app-matrix
    files:
      - widget.env=config/widget.env

  - name: matrix-meetings-bot-env
    namespace: app-matrix
    envs:
      - config/bot.env

  - name: matrix-meetings-config
    namespace: app-matrix
    files:
      - meetings-registration.yaml=config/registration.yaml
